### ISSUE TITLE
Ahorcado: gestión de errores

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/adalab_module_1_project_traditional_games_in_python#12]
Manejar errores cuando la persona envía un input inválido (que no es una letra).

**Comment by carla-caracola** [comment]
@LaiaAyats , añadí un check para que si el usuario ingresa un usuario que no es válido devuelva un mensaje de error y le pida que ingrese otra letra. ¿Lo podés revisar? Gracias!

**Comment by LaiaAyats** [comment]
@carla-caracola, estupendi, hago pull y lo miro!😁
