### ISSUE TITLE
Investigar piedra, papel o tijera

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/adalab_module_1_project_traditional_games_in_python#5]

**Comment by carla-caracola** [comment]
Hola @LaiaAyats ! Estuve viendo lo del juego de piedra, papel o tijeras. De mi parte no veo mayor complejidad, los tips que nos dan son bastante claros y orientativos. Creo que lo mas difícil es implementar la función aleatoria para generar la elección de la máquina, que no es complejo en si, pero no lo usamos antes.
Si te parece podemos quedar mañana por la tarde y lo resolvemos en una sesión de pair-programming.

**Comment by LaiaAyats** [comment]
Carla! me parece bien quedar mañana para resolverlo :) 
Le he estado echando un ojo después de comer y creo que con las últimas funciones que hemos visto (input, while, if...) podemos resolver la mayoría de retos que plantea el juego. 
Voy a intentar escribir algo del código a ver si tiene sentido...mañana te lo enseño y seguro que podemos armar algo chulo! Ánimo ;)
