### ISSUE TITLE
Juego Ahorcado

### ISSUE THREAD

**Issue by carla-caracola** [carla-caracola/adalab_module_1_project_traditional_games_in_python#8]

**Comment by carla-caracola** [comment]
@LaiaAyats he agregado dos funcionalidades que nos faltaban: 
- que funcione con palabras con letras repetidas
- que guarde las letras que ya adivinó el usuario, verifique si vuelve a elegir la misma y muestre un mensaje
Además hice algunas mejoras mas estéticas.
Queda pendiente la parte de manejar errores, por ejemplo cuando la persona envía un input que no es una letra. Por el resto, ya está para revisar. Si lo puedes ver y decirme cualquier cosa, genial. 
Voy a agregar un issue separado para la parte de manejo de errores. 

@YamilleAClavo @910129023 , el ahorcado ya está listo para que lo miren cuando puedan. Sería guay tener vuestro feedback listo antes del final del sprint 2.

**Comment by LaiaAyats** [comment]
Perfecto @carla-caracola, eres una crack! 
Ya hice el pull, lo reviso! :)
